### PR TITLE
Remove deep-copy requirement

### PR DESCRIPTION
**Pull request by matthewcheok**
Seems to pass all tests... We could look into removing lodash next (the other dependency being `_.isFunction`)

### CODE REVIEW

**Comment by siawyoung** [comment]
There's also going to be `_.isMap`, `_.isWeakMap`, etc.

**Comment by siawyoung** [comment]
Just pasting it here:
https://www.npmjs.com/package/lodash.clone
https://www.npmjs.com/package/lodash.ismap
https://www.npmjs.com/package/lodash.isset
https://www.npmjs.com/package/lodash.isweakmap
https://www.npmjs.com/package/lodash.isweakset

**Comment by siawyoung** [comment]
Is this good to go?

**Comment by matthewcheok** [comment]
Yeah let's replace lodash in a separate PR.

**Pull request merged**
